Feature/sniffing 131
NETWAYS/ansible-collection-elasticstack pull request #144
Opened 2023-04-02 14:12 UTC by afeefghannam89

Enable sniffing for logstash
Fix #131

2023-04-02 14:18 UTC, afeefghannam89 commented
When I enable sniffing for Kibana with the version 7 I get the error which I set to you Thomas and elasticsearch hosts will not be listed in the log.
`"message":"ResponseError: security_exception: [security_exception] Reason: missing authentication credentials for REST request [/_nodes/_all/http]\n    at onBody (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:367:23)\n    at IncomingMessage.onEnd (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:291:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}`

With version 8.7 I do not see any changes in kibana log or the listed ealsticsearch host.

2023-04-04 08:11 UTC, widhalmt commented
From what I found on a short research, the API endpoint Kibana uses for sniffing didn't change from 7.x to 8.x . Maybe the role Kibana uses per default didn't allow sniffing?

Since this only affects 7.x and 7.x won't be supported very long, I could live with disabling sniffing in 7.x completely. We could use `if` in the template and then remove the `if` once 7.x has been removed from the code.

2023-04-04 08:24 UTC, afeefghannam89 commented
In version 8 I do not see the listed Elasticsearch hosts in logs, when I enable sniffing, they should be logged, should they? In Logstash I can see the listed Elasticsearch hosts after enabling sniffing. In Kibana It is strange!! 
I use the sniffing options in kibana.yml here https://www.elastic.co/guide/en/kibana/current/settings.html

2023-05-19 07:32 UTC, widhalmt requested changes
Sorry, we had to rename some variables. That broke your changes. I added the new names as "suggestions".

2023-05-19 07:32 UTC, widhalmt commented on roles/elasticsearch/templates/elasticsearch.yml.j2
> +{% if elastic_release | int < 8 or groups['elasticsearch'] | length > 1 %}
```suggestion
{% if elasticstack_release | int < 8 or groups['elasticsearch'] | length > 1 %}
```

We had to rename this variable due to naming conventrion changes.

2023-05-19 07:32 UTC, widhalmt commented on roles/logstash/templates/elasticsearch-output.conf.j2
> +{% if elastic_stack_full_stack | bool and elastic_variant == "elastic" and logstash_sniffing | bool %}
```suggestion
{% if elasticstack_full_stack | bool and elasticstack_variant == "elastic" and logstash_sniffing | bool %}
```
Variables renamed in `main`

2023-05-19 07:32 UTC, widhalmt commented on roles/logstash/templates/elasticsearch-output.conf.j2
> +{% if elastic_stack_full_stack | bool and logstash_security is defined and logstash_security | bool and elastic_variant == "elastic" %}
```suggestion
{% if elasticstack_full_stack | bool and logstash_security is defined and logstash_security | bool and elastic_variant == "elastic" %}
```

Variable renamed in `main`

2023-06-20 14:06 UTC, afeefghannam89 commented
@widhalmt are you ok with the changes here?

2023-06-21 10:50 UTC, widhalmt approved these changes
The full stack variable is still listed as defaulting to `false`. This will be changed globally in https://github.com/NETWAYS/ansible-collection-elasticstack/issues/181 . So yes, I'm very ok with the changes. Thanks. :-)

2023-06-21 10:50 UTC, merged