Feature/remove openssl 138
NETWAYS/ansible-collection-elasticstack pull request #146
Opened 2023-04-02 22:03 UTC by afeefghannam89

Remove the installation of OpenSSL from Elasticsearch role.
Fix #138

2023-04-02 23:27 UTC, afeefghannam89 commented
**Check for cluster status with elastic password** always fails with **full_satck** scenarios for Logstash, Kibana and Beats. This happens in the idempotent check phase, while the cluster status is yellow. I raised the retries to 20, but it does not help. For more information see the **debug** and **fix pipelines**  actions.

On the other hand, this task works fine for elasticsearch pipelines
 Do you have a solution @widhalmt ?

2023-04-03 14:53 UTC, widhalmt requested changes
I just marked a bit of lint. Regarding the cluster not building, I need to have a deeper look into the code. I'll come back for that, too.

2023-04-03 14:53 UTC, widhalmt commented on molecule/kibana_default/prepare.yml
> +
```suggestion
```

Extra blank line

2023-04-03 14:53 UTC, widhalmt commented on roles/elasticsearch/tasks/elasticsearch-security.yml
> +  # no_log: true
Is this still part of testing? Or do you want to keep it for later to have a reference?

2023-04-04 08:11 UTC, afeefghannam89 commented on roles/elasticsearch/tasks/elasticsearch-security.yml
> +  # no_log: true
> Unfortunately the failing checks are hidden when the linter doesn't run through. I don't know why the cluster stays yellow. I just can assume that there's been a minor problem with the `prepare.yml` playbooks. Maybe the nodes can't connect and every node only checks it's local instance?

The same packages which have been installed before will be installed in this scenario. I do delete only RHEL tasks, because we use Ubuntu and compact the installation Tasks to one.

In the debug action you will see the curl call, which is to the localhost not to the remote host.

I can redo the changes and test.

2023-04-04 08:22 UTC, widhalmt commented on roles/elasticsearch/tasks/elasticsearch-security.yml
> +  # no_log: true
Hm, but we run tests on Rocky, too. So we need to test both. As it seems, they run through, though. So that shouldn't be the problem.

2023-04-05 13:10 UTC, afeefghannam89 commented
@widhalmt I have created a new test branch from the actual main branch.  I have removed one empty line in every role and pushed to let the pipelines run for all roles. So the prepare.yml and the complete collection code is unchanged and actual. Anyway the same pipelines for logstash and beats fail with the same reason. That means the changes in this PR are not reason why the pipelines fails, see https://github.com/NETWAYS/ansible-collection-elasticstack/actions/runs/4616563045/jobs/8161826518#step:6:1129

and https://github.com/NETWAYS/ansible-collection-elasticstack/actions/runs/4616563041/jobs/8161756609#step:6:1122

2023-05-15 13:07 UTC, widhalmt approved these changes
Nice. Thank you.

2023-05-15 14:14 UTC, merged