Rename variables to keep naming scheme
NETWAYS/ansible-collection-elasticstack pull request #160
Opened 2023-05-16 11:42 UTC by widhalmt

fixes #159

2023-05-16 11:43 UTC, widhalmt commented
I made this a draft because there are still some variables missing in the renaming. We'll discuss how to proceed with them in #159

2023-05-16 12:46 UTC, widhalmt commented
We opened a discussion around that issue upstream: https://github.com/ansible/ansible-lint/discussions/3451

To move fast, we now put this on the warn_list and come back to it, when
the discussion is resolved. Hopefully to remove the rule completly from
`ansible-lint.yml`.

2023-05-16 12:55 UTC, dgoetz requested changes
If the collection is accepted as prefix in the upstream discussion everything related to the CA shared by the complete stack should be prefixed `elasticstack_`, this goes for unchanged variables like `elastic_ca_pass` and some changed in the PR like `elastic_ca_will_expire_soon`/`elasticsearch_ca_will_expire_soon`. So I would keep thise unchanged until then.

2023-05-16 13:35 UTC, widhalmt commented
@dgoetz I hope, I now caught all of the missing variables. Honestly, I feel a slight hint of panic when I think of merging this PR and all the others that are still open. 😱

2023-05-16 13:37 UTC, widhalmt commented
Some of the checks are failing because of timeouts. As long as all `lint` checks and the required checks work, we should be safe.

2023-05-17 09:41 UTC, afeefghannam89 commented on docs/role-kibana.md
> +* *elasticstack_stack_full_stack*: Use `ansible-role-elasticsearch` as well (default: `false`)
How about remove the first stack word?
```suggestion
* *elasticstack_full_stack*: Use `ansible-role-elasticsearch` as well (default: `false`)
```

2023-05-17 10:04 UTC, afeefghannam89 commented
@widhalmt woo It is a big type work ✍️ Thanks I see the PR is ok. The only suggestion is the above, there are three stack words in the variable name. You can take it or remove it.

2023-05-17 10:13 UTC, afeefghannam89 approved these changes

2023-05-17 11:02 UTC, dgoetz approved these changes
Naming looks consistent now within the collection and with the guideline (including our proposed addition). It creates some clunky names but that seems unavoidable with the goal in mind. Nitpicking could be done in form of complaining some not being in alphabetical or logical order, but I am ok with this.

2023-05-17 11:22 UTC, widhalmt commented
Some of them aren't in alphabetical order on purpose. I tried to group them logically. :-)

2023-05-17 12:49 UTC, merged