Refresh apt cache if package is not yet installed
NETWAYS/ansible-collection-elasticstack pull request #179
Opened 2023-06-15 15:14 UTC by widhalmt

I know, checking for the existence of the configuration directory is not the best way. But it's way faster than quering the package manager every time.

fixes #167

2023-06-16 14:40 UTC, widhalmt commented
It seems like we need to merge #182 before continuing with this.

2023-08-10 12:12 UTC, dnssmr commented
Didn't we fix the tests? Can we merge main?

2023-08-11 10:09 UTC, widhalmt commented
I thought the tests were fixed. :-( As much as I see, tests are still timing out. I don't want to remove the thorough tests we built so far. So I made tests "non mandatory" and check them manually. While this is ultra cumbersome I guess it's the best solution we have so far. Even more so as @martialblog said, we'll have our own GitHub runners soon. And then we'll definitely want our checks back.

So please see the checks "more like guidelines, anyway" and approve if the code makes sense. Even when some checks time out.

2023-08-23 05:45 UTC, dnssmr requested changes
I am a linter

2023-08-23 05:45 UTC, dnssmr commented on roles/beats/tasks/main.yml
> +  apt:
>:(

2023-08-23 05:45 UTC, dnssmr commented on roles/elasticsearch/tasks/main.yml
> +  apt:
Please use fqcn

2023-08-23 05:45 UTC, dnssmr commented on roles/kibana/tasks/main.yml
> +  apt:
! >:(

2023-08-23 05:45 UTC, dnssmr commented on roles/logstash/tasks/main.yml
> +  apt:
Here as well

2023-08-23 08:38 UTC, widhalmt commented
Thanks so much @dnssmr I guess, I'll take a while before I adapted my old brain to this new style of coding. 🤦🏽

2023-08-23 08:43 UTC, widhalmt commented
I hope, I caught all of them, now.

2023-08-23 08:54 UTC, widhalmt commented
I converted this to da draft because the tests found some error that's not just due to problems in GitHub runners. I'll investigate locally and then come back. On the other hand... that's out of the scope of this PR, so I'll disable Draft status. 🤦🏽

2023-10-13 11:06 UTC, dnssmr approved these changes

2023-10-13 19:23 UTC, widhalmt commented
We need #279 merged for this to work and be merged.

2023-10-17 09:39 UTC, merged