Feature/use uri not curl 123
NETWAYS/ansible-collection-elasticstack pull request #186
Opened 2023-06-19 12:37 UTC by dnssmr

2023-06-30 09:23 UTC, dnssmr commented
i dont understand why the test fails, it cant create the logstash user because the password isn't hashable or something? It works locally, can someone look into it? 

Error Message on elasticsearch 7:
< "reason": "Provided password hash uses [NOOP] but the configured hashing algorithm is [BCRYPT]", "root_cause": [{"reason": "Provided password hash uses [NOOP] but the configured hashing algorithm is [BCRYPT]",

Error Message on elasticsearch 8:
> "reason": "The provided password hash is not a hash or it could not be resolved to a supported hash algorithm. The supported password hash algorithms are [bcrypt, bcrypt4, bcrypt5, bcrypt6, bcrypt7, bcrypt8, bcrypt9, bcrypt10, bcrypt11, bcrypt12, bcrypt13, bcrypt14, pbkdf2, pbkdf2_1000, pbkdf2_10000, pbkdf2_50000, pbkdf2_100000, pbkdf2_500000, pbkdf2_1000000, pbkdf2_stretch, pbkdf2_stretch_1000, pbkdf2_stretch_10000, pbkdf2_stretch_50000, pbkdf2_stretch_100000, pbkdf2_stretch_500000, pbkdf2_stretch_1000000]"


Can someone look into it? @widhalmt @afeefghannam89

2023-06-30 10:18 UTC, afeefghannam89 commented
@dnssmr Did I understand correctly, this problem appears only in the pipelines/containers but **NOT** on VMs or servers?

Can you please guide me to the Pipeline or to the place of this issue?

2023-06-30 10:20 UTC, afeefghannam89 commented
@dnssmr I did find it thanks.

2023-07-04 11:18 UTC, afeefghannam89 commented
So I give up here :( I do not understand why setting logstash writer user here has a problem with hashing algorithm! I did really change the algorithm to bcrypt, what is the default by Elastic. But here Elastic do not accept **bcrypt 12** I did not find a way to NOT use version 12.

Locally using **THE SAME CONTAINER** I do not interface this problem.

@dnssmr should I undo my changes?

2023-07-04 11:24 UTC, widhalmt commented
How about https://github.com/NETWAYS/ansible-collection-elasticstack/issues/132 ? If it's "only" a problem with the user management, we can keep `curl` for this single task and later replace it with a module. Changing all other `curl` commands to `uri` is a big benefit by it's own.

2023-07-04 11:37 UTC, afeefghannam89 commented
It is only a problem with GitHub. User management do really work locally without problem on both environments containers and VMs using both distributions Ubuntu and rocky. This problem reminds me with the problem with wait_for tasks.

When we skip adding the logstash writer user, I do not think that the task/s checking for written data in verify.yml will success, do they?

2023-07-04 11:41 UTC, dnssmr commented
@afeefghannam89 @widhalmt i will review the changes later or tomorrow and then test again using command module and curl for this task.

If that works, we can keep it for now, and i will change the molecule tests (there are some curls in command tasks there).

I just don't understand what is wrong here, because it works locally! And the EXACT SAME THING with the role instead of the user works without problem.

2023-07-04 11:42 UTC, afeefghannam89 commented
@widhalmt Sorry I understood you wrong. I did not test keeping command module on this task! As I implement the user encryption in an old branch, the pipeilines did not have problems. Maybe your solution will work.

2023-07-05 13:58 UTC, widhalmt commented
Why it sometimes works and sometimes it doesn't is beyond me, too. I'd suspect different libraries to be installed. But usually Elastics monolithic packages don't use external libraries. And all Ansible related libraries shouldn't have any effects.

To be honest, I really want to know but I don't see any sense in investing enough time to find out where there's a possible workaround.

2023-08-08 15:57 UTC, widhalmt commented
I guess I found a related issue: https://github.com/elastic/elasticsearch/issues/51132 So maybe the process of hashing must be done with another tool / library? It seems, even Elastic isn't completely sure if the hash is compatible or not.

2023-08-09 13:23 UTC, widhalmt commented
I was bold enough to merge this branch with `main` thus incorporating the latest changes @afeefghannam89 made to the testing configuration. I guess now we'll get a way better view at what works and what not.

2023-08-30 06:19 UTC, afeefghannam89 commented
@DanOPT passlib musst be installed when using ‘blowfish’ (BCrypt). This information is availible under[requirements-test.txt](https://github.com/NETWAYS/ansible-collection-elasticstack/pull/186/files#diff-685da804fbcac569d75387e475e57d1de687a54c6c41b3aa4057694cfb5abc4b) but not in the documentaion.

2023-08-30 08:48 UTC, DanOPT commented
> @DanOPT passlib must be installed when using ‘blowfish’ (BCrypt). This information is available under [requirements-test.txt](https://github.com/NETWAYS/ansible-collection-elasticstack/pull/186/files#diff-685da804fbcac569d75387e475e57d1de687a54c6c41b3aa4057694cfb5abc4b) but not in the documentation.

Ok, I missed that it is already in the requirements-test.txt.

2023-09-06 15:12 UTC, widhalmt requested changes
I think I found some small things to be changed. And I had a bundle of questions about some of the user handling tasks. Maybe I'm mislead but I can imagine there's still some old code active that could give us a hard time. Just go through my comments, maybe I'm wrong, then just ignore them.

2023-09-06 15:12 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
> +    security_api_base_url: "https://{{ hostvars[groups['elasticsearch'][0]].ansible_default_ipv4.address }}:{{ elasticstack_elasticsearch_http_port }}/_security/"
```suggestion
    security_api_base_url: "https://{{ hostvars[elasticstack_ca].ansible_default_ipv4.address }}:{{ elasticstack_elasticsearch_http_port }}/_security/"
```
Could that work, too? That would make the code a bit more streamlined and easier to maintain.

2023-09-06 15:12 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
> +    security_api_base_url: "https://{{ hostvars[groups['elasticsearch'][0]].ansible_default_ipv4.address }}:{{ elasticstack_elasticsearch_http_port }}/_xpack/security/"
```suggestion
    security_api_base_url: "https://{{ hostvars[elasticstack_ca].ansible_default_ipv4.address }}:{{ elasticstack_elasticsearch_http_port }}/_xpack/security/"
```

Same as above

2023-09-06 15:12 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
> +  failed_when: false
Shouldn't a failed call to the API break the workflow? Ok, I see, the next task will fail when the variable isn't set.

2023-09-06 15:12 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
>    failed_when: false
Same here. I'm not sure if this task shouldn't fail. But, of course, the next will fail when there's no information about the user available.

2023-09-06 15:12 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
> +  failed_when: not put_logstash_writer_role_response.json.role.created
```suggestion
  failed_when: not put_logstash_writer_role_response.json.role.created | bool
```

I guess it's returning `true`if it works, doesn't it?

2023-09-06 15:34 UTC, afeefghannam89 commented on README.md
>  We test the collection on the following Linux distributions. Each one with Elastic Stack 7 and 8.
If you mean the new added Linux distributions in Docs, no we have these tests hier https://github.com/NETWAYS/ansible-collection-elasticstack/blob/main/.github/workflows/test_full_stack.yml#L36

2023-09-06 15:35 UTC, afeefghannam89 commented on docs/role-logstash.md
> +* `passlib` if you do not disable password hashing for logstash user.
Related to the question above.

2023-09-06 15:38 UTC, afeefghannam89 commented on roles/elasticsearch/tasks/main.yml
> +      register: result
Good hint, I did not notice it, I will change it

2023-09-06 15:38 UTC, afeefghannam89 commented on roles/elasticsearch/tasks/main.yml
> -      no_log: "{{ elasticstack_no_log }}"
you are right

2023-09-06 15:42 UTC, afeefghannam89 commented on roles/logstash/tasks/logstash-security.yml
> +  failed_when: false
No, the next task will not fail if the variable is not set or the call fails, because of the when condition

2023-09-06 15:45 UTC, afeefghannam89 commented on roles/logstash/tasks/logstash-security.yml
>    failed_when: false
No because we are using *defined* in the condition. When it is not defined because the user is not set jet, set fact will be skipped, and the role will continue.

2023-09-07 06:10 UTC, afeefghannam89 commented on README.md
> +* `passlib` if you do not disable password hashing for logstash user.
I undo the changes

2023-09-07 06:10 UTC, afeefghannam89 commented on README.md
>  We test the collection on the following Linux distributions. Each one with Elastic Stack 7 and 8.
I undo the changes

2023-09-07 06:10 UTC, afeefghannam89 commented on docs/role-logstash.md
> +* `passlib` if you do not disable password hashing for logstash user.
I undo the changes

2023-09-07 06:11 UTC, afeefghannam89 commented on roles/elasticsearch/tasks/main.yml
> -      no_log: "{{ elasticstack_no_log }}"
Done ;)

2023-09-07 06:11 UTC, afeefghannam89 commented on roles/elasticsearch/tasks/main.yml
> +      register: result
Done

2023-09-07 06:11 UTC, afeefghannam89 commented on roles/logstash/tasks/logstash-security.yml
> +    security_api_base_url: "https://{{ hostvars[groups['elasticsearch'][0]].ansible_default_ipv4.address }}:{{ elasticstack_elasticsearch_http_port }}/_security/"
Done ;)

2023-09-07 06:11 UTC, afeefghannam89 commented on roles/logstash/tasks/logstash-security.yml
> +    security_api_base_url: "https://{{ hostvars[groups['elasticsearch'][0]].ansible_default_ipv4.address }}:{{ elasticstack_elasticsearch_http_port }}/_xpack/security/"
Done :)

2023-09-07 06:12 UTC, afeefghannam89 commented on roles/logstash/tasks/logstash-security.yml
> +  failed_when: not put_logstash_writer_role_response.json.role.created
Done

2023-09-07 07:43 UTC, widhalmt commented on README.md
>  We test the collection on the following Linux distributions. Each one with Elastic Stack 7 and 8.
Sorry, I missed the tests. Thanks you for pointing out.

2023-09-07 07:45 UTC, widhalmt commented on README.md
> +* `passlib` if you do not disable password hashing for logstash user.
No, we should highlight both. But The text says something about "you need the following roles". So I think, we need one section for roles/collections and one for packages/libraries.

2023-09-07 07:45 UTC, widhalmt commented on roles/elasticsearch/tasks/main.yml
> -      no_log: "{{ elasticstack_no_log }}"
Thanks. :-)

2023-09-07 07:45 UTC, widhalmt commented on roles/elasticsearch/tasks/main.yml
> +      register: result
Thanks. :-)

2023-09-07 07:46 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
> +    security_api_base_url: "https://{{ hostvars[groups['elasticsearch'][0]].ansible_default_ipv4.address }}:{{ elasticstack_elasticsearch_http_port }}/_security/"
Nice. :)

2023-09-07 07:46 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
> +    security_api_base_url: "https://{{ hostvars[groups['elasticsearch'][0]].ansible_default_ipv4.address }}:{{ elasticstack_elasticsearch_http_port }}/_xpack/security/"
Yeah. :-)

2023-09-07 07:48 UTC, afeefghannam89 commented on roles/logstash/tasks/logstash-security.yml
>    failed_when: false
I will test somthing

2023-09-07 07:49 UTC, afeefghannam89 commented on roles/logstash/tasks/logstash-security.yml
> +  failed_when: false
I will test something and come back :)

2023-09-07 07:57 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
> +  failed_when: false
Ok, thanks for clarifying.

2023-09-07 07:57 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
>    failed_when: false
Ok. Standing by. :-)

2023-09-07 08:22 UTC, afeefghannam89 commented on roles/logstash/tasks/logstash-security.yml
> +  failed_when: false
After testing: We have to let changed_when: false to not get error that the user/role does not exists and the collection run break

2023-09-07 08:22 UTC, afeefghannam89 commented on roles/logstash/tasks/logstash-security.yml
>    failed_when: false
Same result as above :)

2023-09-07 09:15 UTC, widhalmt requested changes
One last, minor, cosmetical change. I promise. ;-)

2023-09-07 09:15 UTC, widhalmt commented on README.md
> +* `passlib` Python library if you do not disable password hashing for logstash user and you want to use logstash role from this collection. It should be installed with pip on the Ansible controller.
```suggestion

You will need these packages / libraries installed. Some very basic packages like `openssl` get handled by the collection if needed. The following list contains packages and libraries which only apply to special cases or need for you to decide on the installation method.

* `passlib` Python library if you do not disable password hashing for logstash user and you want to use logstash role from this collection. It should be installed with pip on the Ansible controller.
```

2023-09-07 09:15 UTC, widhalmt commented on docs/role-logstash.md
> +* `passlib` Python library if you do not disable password hashing for logstash user. It should be installed with pip on the Ansible controller.
```suggestion

You will need these packages / libraries installed. Some very basic packages like `openssl` get handled by the collection if needed. The following list contains packages and libraries which only apply to special cases or need for you to decide on the installation method.

* `passlib` Python library if you do not disable password hashing for logstash user. It should be installed with pip on the Ansible controller.
```

2023-09-07 09:26 UTC, afeefghannam89 commented on README.md
> +* `passlib` Python library if you do not disable password hashing for logstash user and you want to use logstash role from this collection. It should be installed with pip on the Ansible controller.
No problem done.

2023-09-07 09:27 UTC, afeefghannam89 commented on docs/role-logstash.md
> +* `passlib` Python library if you do not disable password hashing for logstash user. It should be installed with pip on the Ansible controller.
Done :)

2023-09-07 09:39 UTC, widhalmt approved these changes
Perfect! Thanks a lot to @dnssmr and @afeefghannam89 for that herculean deed.

2023-09-07 13:06 UTC, merged