Fixed a typo.
NETWAYS/ansible-collection-elasticstack pull request #221
Opened 2023-08-09 10:47 UTC by widhalmt

Thanks @xtruthx for finding it.

fixes #217

2023-08-09 12:13 UTC, widhalmt commented
Checks failing due to problems in GitHub test infrastructure or being too excessive with tests.

2023-08-10 09:37 UTC, Donien requested changes
I've found some more `ealstic`

2023-08-10 09:37 UTC, Donien commented on docs/role-elasticsearch.md
>  * *ealsticsearch_http_publish_port*: (integer) The port of the HTTP publish address. Configure this setting only if you need the publish port to be different from http.port. (default: `not set`)
Another `ealstic`

2023-08-10 09:37 UTC, Donien commented on roles/elasticsearch/templates/elasticsearch.yml.j2
>  http.publish_port: {{ ealsticsearch_http_publish_port }}
Another two `ealstic`s

2023-08-10 12:08 UTC, Donien approved these changes
Looks good to me now 👍🏻

2023-08-10 12:42 UTC, dnssmr approved these changes

2023-08-10 12:50 UTC, merged