Replace quotations for passwords with special characters
NETWAYS/ansible-collection-elasticstack pull request #285
Opened 2023-10-11 16:10 UTC by widhalmt

Using special characters like `$` in some passwords breaks the role. This PR introduces a test (by setting passwords with special characters) and introduces a fix to handle them correctly.

fixes #282

2023-10-11 18:02 UTC, ivareri commented
I haven't tested, but is there a reason not to use  [`ansible.builtin.command`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html) instead of `shell` for this?

Something like this might work
```YAML
- name: Set bootstrap password
  ansible.builtin.command: /usr/share/elasticsearch/bin/elasticsearch-keystore add -x 'bootstrap.password'
  args:
    stdin: {{ elasticsearch_bootstrap_pw }}
  when: "'bootstrap.password' not in elasticsearch_keystore.stdout_lines"
```

2023-10-11 19:15 UTC, widhalmt commented
> I haven't tested, but is there a reason not to use [`ansible.builtin.command`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html) instead of `shell` for this?
> 
> Something like this might work
> 
> ```yaml
> - name: Set bootstrap password
>   ansible.builtin.command: /usr/share/elasticsearch/bin/elasticsearch-keystore add -x 'bootstrap.password'
>   args:
>     stdin: {{ elasticsearch_bootstrap_pw }}
>   when: "'bootstrap.password' not in elasticsearch_keystore.stdout_lines"
> ```

To be honest, I don't see a reason. Maybe the contributer back then had an idea I do not recognize. I guess, in the current implementation, command should be fine and make things even faster.

In the long term, it might be a good idea to replace these tasks with a custom module, though.

2024-02-09 16:57 UTC, widhalmt commented
@ivareri I guess it was that the original contributor (like me) didn't think of the possibility to implement it with `stdin`.

I still think this would fit into another PR so not to change too many things at once. Maybe a module would be even better.

2024-06-07 06:56 UTC, tbauriedel approved these changes

2026-06-24 16:17 UTC, afeefghannam89 requested changes
The suggestion of @ivareri with command module is the best one because:
- There is no Shell in between when writing the password in the store. when auditd + execve enabled, the password will be plain in the logs.
- When the password has single quote will not be a problem. stdin accept everything

2026-06-25 17:02 UTC, afeefghannam89 commented
Complated with #470

2026-06-25 17:02 UTC, closed without merging