make elasticsearch group name configurable
NETWAYS/ansible-collection-elasticstack pull request #305
Opened 2024-01-22 10:57 UTC by zerwes

For my setup I need multiple `single-node` instances, and here I get into trouble with the hard coded group name.
This fixes this limitation for the `elasticsearch` role only.
If it is desired, I can implemented it for all roles ...

2024-01-26 16:27 UTC, widhalmt requested changes
Wow, thank you. That's a real nice addition. I had the same problem a few times but always got away with different inventories. Your approach will safe a lot of headache for a lot of people.

Only one real change I want to request. You couldn't know and we have to make it more prominent in the documentation: We're trying to stick to the new nomenclature for variables Ansible is using. Every variable defined in a role has to start with the name of the role. I know, there're some "elasticstack" variables but we will fix that in #250 .

The fix will bring yet another role "elasticstack" that will be imported by every other role. And it will mostly set default, variables and facts. Until this PR is merged, please rename your new variable to something like `elasticstack_elasticsearch_group_name` or `elasticstack_es_group_name`. For now you have to set it in every role like you already do. But we will move it to the new "global" role.

I guess, changing the name with `grep`, `find` and `sed` might work. Please let me know if I can help with that.

And please add your new variable to the list of variables, too. I really appreciate your change to the documentation but I hope to have the list as consistent as possible.

You offered to have the same change for all roles. This would actually be great and very much appreciated.

Thanks for your work so far.

2024-01-26 16:27 UTC, widhalmt commented on README.md
> +_Note_: The roles rely on hardcoded group names for placing services on hosts. Please make sure you have groups named `elasticsearch` (or define your desired group name using the var `elasticsearch_g
I'm wondering if "hardcoded" is still valid here. But since most are still hardcoded, I guess, you can just go with it.

2024-01-26 16:27 UTC, widhalmt commented on molecule/elasticsearch_no-security/verify.yml
> +    elasticsearch_group_name: elasticsearch
Could you just make it a default? Then you don't have to set it here. Or, you could set it to a totally different value and test your changes with molecule right away. I guess, I prefer the tested change. :-)

2024-01-26 16:27 UTC, widhalmt commented on roles/beats/defaults/main.yml
> +elasticsearch_group_name: elasticsearch
Please use another name for the group. We're trying to stick to Ansible standards where a variable has to start with the name of the role.

I know, there are "elasticstack" variables, but I'll go into detail in the summary comment.

2024-01-27 10:25 UTC, zerwes commented
> please rename your new variable to something like `elasticstack_elasticsearch_group_name`

done in 17d8240

2024-01-27 10:33 UTC, zerwes commented on README.md
> +_Note_: The roles rely on hardcoded group names for placing services on hosts. Please make sure you have groups named `elasticsearch` (or define your desired group name using the var `elasticsearch_g
> But since most are still hardcoded ...

As I wrote: if you like I can try to implement this for all other roles (I have to admit, for now I just use multiple instances of the elasticsearch group, so it would be kind of dry swimming exercises, but if desired, I can implement this in order to make it consistent generic.
I have this issue in general with cluster related roles (galera, haproxy, keepalive) where you can have multiple instances of multinode clusters where you have to aggregate the cluster nodes via a generic named var.
So just let me know if it is desired to continue with the other group names.
Otherwise I think you are right, as most of them will remain hard coded, the phrasing can stay this way.

2024-01-28 04:39 UTC, zerwes commented on molecule/elasticsearch_no-security/verify.yml
> +    elasticsearch_group_name: elasticsearch
well, I hope 808ed67 is the desired state and I didn't misunderstand anything

2024-02-04 11:05 UTC, zerwes commented on README.md
> +_Note_: The roles rely on hardcoded group names for placing services on hosts. Please make sure you have groups named `elasticsearch` (or define your desired group name using the var `elasticsearch_g
Hello @widhalmt 

on the branch https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-collection-elasticstack/tree/feature/make-all-group-names-configurable I have renamed all hard coded group names.
The tests run all fine. If desired, I can merge the branch into the PR branch

```diff
~/git/ansible-collection-elasticstack feature/make-all-group-names-configurable* ± git diff feature/make-elasticsearch-group-name-configurable | cat
diff --git a/roles/beats/defaults/main.yml b/roles/beats/defaults/main.yml
index 37ec79a..490eb61 100644
--- a/roles/beats/defaults/main.yml
+++ b/roles/beats/defaults/main.yml
@@ -64,6 +64,7 @@ elasticstack_variant: elastic
 elasticstack_security: true
 
 elasticstack_elasticsearch_group_name: elasticsearch
+elasticstack_logstash_group_name: logstash
 
 elasticstack_ca_dir: /opt/es-ca
 elasticstack_ca_pass: PleaseChangeMe
diff --git a/roles/beats/templates/auditbeat.yml.j2 b/roles/beats/templates/auditbeat.yml.j2
index 08d8451..3cf82f2 100644
--- a/roles/beats/templates/auditbeat.yml.j2
+++ b/roles/beats/templates/auditbeat.yml.j2
@@ -53,7 +53,7 @@ output.elasticsearch:
 {% if beats_auditbeat_output == "logstash" %}
 output.logstash:
 {% if elasticstack_full_stack | bool %}
-  hosts: [ {% for host in groups['logstash'] %}"{{ host }}:{{ elasticstack_beats_port }}"{% if not loop.last %},{% endif %}{% endfor %}]
+  hosts: [ {% for host in groups[elasticstack_logstash_group_name] %}"{{ host }}:{{ elasticstack_beats_port }}"{% if not loop.last %},{% endif %}{% endfor %}]
 {% else %}
   hosts: [ {% for host in beats_target_hosts %}"{{ host }}:{{ elasticstack_beats_port }}"{% if not loop.last %},{% endif %}{% endfor %}]
 {% endif %}
diff --git a/roles/beats/templates/filebeat.yml.j2 b/roles/beats/templates/filebeat.yml.j2
index d5a6ce5..f7457cf 100644
--- a/roles/beats/templates/filebeat.yml.j2
+++ b/roles/beats/templates/filebeat.yml.j2
@@ -128,7 +128,7 @@ output.elasticsearch:
 {% if beats_filebeat_output == "logstash" %}
 output.logstash:
 {% if elasticstack_full_stack | bool %}
-  hosts: [ {% for host in groups['logstash'] %}"{{ host }}:{{ elasticstack_beats_port }}"{% if not loop.last %},{% endif %}{% endfor %}]
+  hosts: [ {% for host in groups[elasticstack_logstash_group_name] %}"{{ host }}:{{ elasticstack_beats_port }}"{% if not loop.last %},{% endif %}{% endfor %}]
 {% else %}
   hosts: [ {% for host in beats_target_hosts %}"{{ host }}:{{ elasticstack_beats_port }}"{% if not loop.last %},{% endif %}{% endfor %}]
 {% endif %}
diff --git a/roles/beats/templates/metricbeat.yml.j2 b/roles/beats/templates/metricbeat.yml.j2
index a8f0642..138eecf 100644
--- a/roles/beats/templates/metricbeat.yml.j2
+++ b/roles/beats/templates/metricbeat.yml.j2
@@ -30,7 +30,7 @@ output.elasticsearch:
 {% if beats_metricbeat_output == "logstash" %}
 output.logstash:
 {% if elasticstack_full_stack | bool %}
-  hosts: [ {% for host in groups['logstash'] %}"{{ host }}:{{ elasticstack_beats_port }}"{% if not loop.last %},{% endif %}{% endfor %}]
+  hosts: [ {% for host in groups[elasticstack_logstash_group_name] %}"{{ host }}:{{ elasticstack_beats_port }}"{% if not loop.last %},{% endif %}{% endfor %}]
 {% else %}
   hosts: [ {% for host in beats_target_hosts %}"{{ host }}:{{ elasticstack_beats_port }}"{% if not loop.last %},{% endif %}{% endfor %}]
 {% endif %}
diff --git a/roles/elasticsearch/defaults/main.yml b/roles/elasticsearch/defaults/main.yml
index 9c3f72d..4fa7c74 100644
--- a/roles/elasticsearch/defaults/main.yml
+++ b/roles/elasticsearch/defaults/main.yml
@@ -63,3 +63,5 @@ elasticstack_elasticsearch_http_port: 9200
 elasticstack_no_log: true
 
 elasticstack_elasticsearch_group_name: elasticsearch
+elasticstack_logstash_group_name: logstash
+elasticstack_kibana_group_name: kibana
diff --git a/roles/elasticsearch/handlers/main.yml b/roles/elasticsearch/handlers/main.yml
index ff3b5ab..7816973 100644
--- a/roles/elasticsearch/handlers/main.yml
+++ b/roles/elasticsearch/handlers/main.yml
@@ -12,9 +12,10 @@
 
 - name: Restart kibana if available for elasticsearch certificates
   ansible.builtin.include_tasks: handlers/restart_kibana.yml
-  with_items: "{{ groups['kibana'] }}"
+  with_items: "{{ groups[elasticstack_kibana_group_name] }}"
   when:
     - elasticstack_full_stack: true
     - "not 'renew_ca' in ansible_run_tags"
     - "not elasticstack_ca_will_expire_soon | bool"
-    - groups['kibana'] is defined
+    - elasticstack_kibana_group_name is defined
+    - groups[elasticstack_kibana_group_name] is defined
diff --git a/roles/elasticsearch/tasks/elasticsearch-security.yml b/roles/elasticsearch/tasks/elasticsearch-security.yml
index 26c99c7..256e659 100644
--- a/roles/elasticsearch/tasks/elasticsearch-security.yml
+++ b/roles/elasticsearch/tasks/elasticsearch-security.yml
@@ -61,11 +61,12 @@
   ansible.builtin.service:
     name: logstash
     state: stopped
-  with_items: "{{ groups['logstash'] }}"
+  with_items: "{{ groups[elasticstack_logstash_group_name] }}"
   delegate_to: "{{ item }}"
   when:
     - "'renew_ca' in ansible_run_tags or elasticstack_ca_will_expire_soon | bool"
-    - groups['logstash'] is defined
+    - elasticstack_logstash_group_name is defined
+    - groups[elasticstack_logstash_group_name] is defined
 
 - name: Backup ca directory on elasticsearch ca host then remove
   when: (inventory_hostname == elasticstack_ca) and ('renew_ca' in "ansible_run_tags" or elasticstack_ca_will_expire_soon | bool)
```

2024-02-04 11:09 UTC, zerwes commented
while renaming the remaining hard coded group names, i stumbled over `elasticsearch_role_master` ...
```shell
~/git/ansible-collection-elasticstack feature/make-all-group-names-configurable* ± git grep "groups\['elasticsearch_role_master']"
roles/elasticsearch/tasks/main.yml:        count_of_master_nodes: "{{ groups['elasticsearch_role_master'] | length }}"
roles/elasticsearch/templates/elasticsearch.yml.j2:cluster.initial_master_nodes: [ {% for host in groups['elasticsearch_role_master']  %}
```
I did not dive deeper into this, but I think this should be configurable too, am I right?

2024-02-09 17:12 UTC, widhalmt commented on README.md
> +_Note_: The roles rely on hardcoded group names for placing services on hosts. Please make sure you have groups named `elasticsearch` (or define your desired group name using the var `elasticsearch_g
Yes, please do so. I'll wait with merging until you give the OK.

2024-02-09 17:15 UTC, widhalmt commented
> while renaming the remaining hard coded group names, i stumbled over `elasticsearch_role_master` ...
> 
> ```shell
> ~/git/ansible-collection-elasticstack feature/make-all-group-names-configurable* ± git grep "groups\['elasticsearch_role_master']"
> roles/elasticsearch/tasks/main.yml:        count_of_master_nodes: "{{ groups['elasticsearch_role_master'] | length }}"
> roles/elasticsearch/templates/elasticsearch.yml.j2:cluster.initial_master_nodes: [ {% for host in groups['elasticsearch_role_master']  %}
> ```
> 
> I did not dive deeper into this, but I think this should be configurable too, am I right?

Yes, you're totally right. I never liked these hardcoded roles. I guess, I just had a hard time getting rid of them after I started.

2024-02-21 12:07 UTC, zerwes commented on README.md
> +_Note_: The roles rely on hardcoded group names for placing services on hosts. Please make sure you have groups named `elasticsearch` (or define your desired group name using the var `elasticsearch_g
Hello @widhalmt 
sorry for the delay ... somehow the github notification mails did not reach me in the last weeks, so I did not realized your comments
Well, the merge is done

2024-03-08 14:39 UTC, widhalmt requested changes
@zerwes Everything approved. But the PR now has merge conflicts. Can you fix them? If you want help, please just let me know.

2024-03-16 10:11 UTC, zerwes commented
> @zerwes Everything approved. But the PR now has merge conflicts. Can you fix them? If you want help, please just let me know.

@widhalmt : merge conflicts resolved in 29c802b 
for my part, the checks are green and OK on the fork ...

2024-04-15 18:48 UTC, zerwes commented
Hello @widhalmt 
Is there anything I can do here?
Greetings

2024-04-17 13:09 UTC, widhalmt commented
Hi @zerwes , not really. I was hoping the checks would start eventually. I'll see into it that you finally get your PR merged. It's quite useful nonetheless. Thank you again for all the work and sorry for taking so long.

2024-04-17 13:09 UTC, merged