Add elasticsearch_role module
NETWAYS/ansible-collection-elasticstack pull request #308
Opened 2024-01-31 20:06 UTC by tbauriedel

First draft for a elasticsearch_role module.

Feedback needed if something is missing.
Documentation needs to be added also.

Example Usage:
```
    - name: Create role
      netways.elasticstack.elasticsearch_role:
        name: new-role
        cluster:
          - manage_own_api_key
          - delegate_pki
        indicies:
          - names:
              - foobar321
              - barfoo123
            privileges:
              - read
              - write
        state: present
        host: https://localhost:9200
        auth_user: elastic
        auth_pass: changeMe123!
        verify_certs: false
        ca_certs: /etc/elasticsearch/certs/http_ca.crt

```

2024-02-01 13:48 UTC, tbauriedel commented
Example usage for the elasticsearch_user module:
```
- name: Create elasticsearch user 'new-user'
      netways.elasticstack.elasticsearch_user:
        name: new-user1
        fullname: New User
        password: changeMe123!
        email: new@user.de
        roles:
          - new-role1
          - logstash-writer
        enabled: true
        state: present
        host: https://localhost:9200
        auth_user: elastic
        auth_pass: changeMe321!
        verify_certs: false
```

2024-02-01 13:53 UTC, tbauriedel commented
@widhalmt since that modules where requested from your side, could you please have a look at it? Maybe test them also.

2024-02-01 14:59 UTC, widhalmt commented
I have local testing environments and I will put this change through a few tests. I'm the wrong person to review the code of the module (yet) but I can do integration tests and check everything around the module.

2024-02-01 15:06 UTC, lcndsmr commented
Genuine question: why would we need a module which calls upon a role? I have never seen this before, is this commonly done?

2024-02-01 15:14 UTC, tbauriedel commented
Inspiration for the two modules comes from [here](https://github.com/NETWAYS/ansible-collection-elasticstack/blob/main/roles/logstash/tasks/logstash-security.yml#L405-L472), for example.
Roles and users are repeatedly created in the collection via several tasks so that the needed component has a user in Elastic.
In order to be able to do this cleanly and not always require several tasks with requests, etc., these modules were requested.

With them you can easily create, update and delete them.

Sure, you could do this in your Kibana. But we have some known customers which do this all within the collection (or want to)

The whole thing has turned into a discussion of principles, as the idea of creating an internal Elastic user within the Logstash role is somewhat at odds with the idea of separating roles. However, this will be addressed later and assumed as a requirement.

2024-02-05 14:28 UTC, lcndsmr requested changes

2024-02-07 11:41 UTC, lcndsmr commented on plugins/module_utils/elasticsearch_role.py
> +        if pre_role != None:
You can un-nest here too, if you return when pro_role == None

The rest looks a lot better!

2024-02-07 12:56 UTC, lcndsmr requested changes
Code looks amazing, but it has to be testet now, and I don'Ät know how to withdraw approval :D

2024-02-07 13:11 UTC, tbauriedel commented
I have already implemented a [workflow](https://github.com/NETWAYS/ansible-collection-elasticstack/actions/runs/7814309143/job/21315311813?pr=308) to test the modules.

@lcndsmr I guess you can remove the change request now. I have requested Thomas for review. As long as he dont approve it, it should be finde. Auto-merging is also not enabled for this PR.

@widhalmt would you please give us a last "okay it works"? :)

2024-02-07 16:22 UTC, lcndsmr approved these changes

2024-02-12 12:40 UTC, widhalmt requested changes
I found a few minor issues and had one extra question. Those aside: THANK YOU.

2024-02-12 12:40 UTC, widhalmt commented on docs/module-elasticsearch_role.md
> +* *verify_certs*: Verify certificates (Default: True)
```suggestion
* *verify_certs*: Verify certificates (Default: `true`)
```
Just a style change.

2024-02-12 12:40 UTC, widhalmt commented on .gitignore
> +.vscode
```suggestion
.vscode
```
Missing `newline` at the end of the file

2024-02-12 12:40 UTC, widhalmt commented on docs/module-elasticsearch_user.md
> +* *verify_certs*: Verify certificates (Default: True)
```suggestion
* *verify_certs*: Verify certificates (Default: `true`)
```
Style change

2024-02-12 12:40 UTC, widhalmt commented on molecule/elasticsearch_test_modules/converge.yml
> +    #elasticsearch_security: true # needed for tests of > 7 releases
```suggestion
```
If we don't need it anymore, please remove it

2024-02-12 12:40 UTC, widhalmt commented on molecule/elasticsearch_test_modules/prepare.yml
> +        - certifi
Do we need this module only for tests or also for production? Maybe it's missing from the docs?

2024-02-12 12:40 UTC, widhalmt commented on plugins/module_utils/api.py
> +        return Elasticsearch(hosts=[host], basic_auth=(auth_user, auth_pass), ssl_context=ctx, verify_certs=verify_certs)
```suggestion
        return Elasticsearch(hosts=[host], basic_auth=(auth_user, auth_pass), ssl_context=ctx, verify_certs=verify_certs)
```
Missing newline

2024-02-12 14:42 UTC, widhalmt approved these changes
Thanks for the initial code. And the reaction to my picky requests. Approved.

2024-02-12 15:03 UTC, merged