replace user and role creation with corresponding modules
NETWAYS/ansible-collection-elasticstack pull request #323
Opened 2024-05-27 07:49 UTC by christoph2497

I replaced the old functionality of creating users and roles of logstash with the corresponding modules. Also i added a few new variables to default/main.yml which are used to make the user and role creation more variable. The documenation was also adjusted accordingly.

2024-05-27 08:00 UTC, tbauriedel requested changes

2024-05-27 08:00 UTC, tbauriedel commented on roles/logstash/tasks/logstash-security.yml
> +
double blank line

2024-05-27 08:03 UTC, christoph2497 commented on roles/logstash/defaults/main.yml
> +logstash_email: new@user.de
i will try that

2024-05-27 08:03 UTC, tbauriedel requested changes

2024-05-27 08:03 UTC, tbauriedel commented on roles/logstash/tasks/logstash-security.yml
> +    host: https://localhost:9200
should not be hardcoded.
Maybe you can steal something [here](https://github.com/NETWAYS/ansible-collection-elasticstack/blob/main/roles/logstash/tasks/logstash-security.yml#L378)

2024-05-27 08:03 UTC, tbauriedel commented on roles/logstash/tasks/logstash-security.yml
> +    host: https://localhost:9200
should not be hardcoded.
Maybe you can steal something [here](https://github.com/NETWAYS/ansible-collection-elasticstack/blob/main/roles/logstash/tasks/logstash-security.yml#L378)

2024-05-27 08:03 UTC, tbauriedel commented on roles/logstash/tasks/logstash-security.yml
> +- name: Create user
Task name should be more informative

2024-05-27 08:03 UTC, tbauriedel commented on roles/logstash/tasks/logstash-security.yml
> +        privileges:
Perhaps we should also consider casting these lines into a variable here.
Same like for "logstash_user_indices"

2024-05-27 08:03 UTC, tbauriedel commented on roles/logstash/tasks/logstash-security.yml
> +    cluster:
Perhaps we should also consider casting these lines into a variable here.
Same like for "logstash_user_indices"

2024-05-27 08:04 UTC, christoph2497 commented on roles/logstash/tasks/logstash-security.yml
> +          - logstash_user_indices
i adopted this from the role jinja template

2024-05-27 08:06 UTC, tbauriedel commented on roles/logstash/tasks/logstash-security.yml
> +          - logstash_user_indices
I don't think it will resolve the argument, it will pass "logstash_user_indices" as a string and distribute it as a permission.
The strings within the variable are then omitted here.

2024-05-27 08:08 UTC, tbauriedel commented
Since we want to use these modules and the need the python3 module "elasticsearch", we should consider to install the module as part of the role.

2024-05-27 09:00 UTC, christoph2497 commented on roles/logstash/tasks/logstash-security.yml
> +
fixed with e42504d

2024-05-27 09:24 UTC, christoph2497 commented on roles/logstash/tasks/logstash-security.yml
> +          - logstash_user_indices
you are right, i have to adjust this that it uses the variable instead

2024-05-31 10:17 UTC, tbauriedel approved these changes
LGTM

2024-05-31 10:22 UTC, tbauriedel approved these changes

2024-05-31 10:23 UTC, tbauriedel approved these changes

2024-05-31 10:23 UTC, tbauriedel submitted a review, later dismissed

2024-05-31 10:24 UTC, tbauriedel commented
Another review is needed because I have added some changes...
Ping @widhalmt

2024-06-05 12:53 UTC, widhalmt requested changes
I found a view things that *might* need to be changed.

Please make sure installing the packagaes really works on all operating systems. And maybe move the installation to the `elasticstack` role so we don't have to run the same code every time we need to handle users.

2024-06-05 12:53 UTC, widhalmt commented on docs/role-logstash.md
> +* *logstash_user_password*: Password of Elasticsearch user. It must be at least 6 characters long (default: `password`)
```suggestion
* *logstash_user_password*: Password of `logstash_user` in Elasticsearch. It must be at least 6 characters long (default: `password`)
```
I know, this was already wrong before the change. But please use the chance to fix it.

2024-06-05 12:53 UTC, widhalmt commented on docs/role-logstash.md
> +* *logstash_role_indicies_privileges*: Indices the role has access to (default: `"write", "create", "delete", "create_index", "manage", "manage_ilm"`)
```suggestion
* *logstash_role_indicies_privileges*: Index permissions the role has on `logstash_role_indicies_names`: (default: `"write", "create", "delete", "create_index", "manage", "manage_ilm"`)
```
I guess, that was just a copy&paste error.

2024-06-05 12:53 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
> +    host: "https://{{ hostvars[elasticstack_ca].ansible_default_ipv4.address }}:{{ elasticstack_elasticsearch_http_port }}"
This will not work on clusters with security disabled. But since we will to have support for them soon, anyway, I'm ok with not creating another version without authentication.

2024-06-05 12:53 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
> +    verify_certs: false
```suggestion
    verify_certs: true
```
Please!

2024-06-05 12:53 UTC, widhalmt commented on roles/logstash/tasks/main.yml
> +    name: ["python3", "python3-pip"]
```suggestion
    name: 
      - python3
      - python3-pip
```
Matches our other code. And it's easier readable as well as easier maintainable.

Are you sure, this will work on all supported operating systems? I thought, package names are different.

2024-06-05 13:03 UTC, tbauriedel commented on roles/logstash/tasks/main.yml
> +    name: ["python3", "python3-pip"]
Well, all checks have passed. 
If we have checks for all supported systems it should be fine. If not, we will have to build checks for the missing one.

2024-06-05 13:05 UTC, tbauriedel commented on docs/role-logstash.md
> +* *logstash_user_password*: Password of Elasticsearch user. It must be at least 6 characters long (default: `password`)
Since the user name isnt hardcoded anymore I would not mention the previous hardcoded username in the doc. I would go with something like "Password of logstash user in Elasticsearch".
Mentioning the `logstash_user` inside of the doc could be misleading if you dont use the default name.

2024-06-07 06:55 UTC, tbauriedel commented
Pipelines failing to bug #326

2024-06-07 08:25 UTC, tbauriedel commented
(Ansible verbosity 3 needs to be removed before merging)

2024-06-07 11:36 UTC, widhalmt approved these changes
Looks good to me. No objections from my side.

2024-06-07 11:51 UTC, merged