use ansible DEFAULT_LOCAL_TMP for files stored on the ansible controller
NETWAYS/ansible-collection-elasticstack pull request #355
Opened 2024-11-11 02:52 UTC by zerwes

https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-local-tmp

closes #354

2024-11-15 14:11 UTC, widhalmt requested changes
Oh, very good find! Thank you for the contribution.

I just found some tiny bits of lint. Could you please fix them and then I'll merge.

2024-11-15 14:11 UTC, widhalmt commented on roles/elasticsearch/tasks/elasticsearch-security.yml
> +        path:  "{{ lookup('config', 'DEFAULT_LOCAL_TMP') | dirname }}/{{ ansible_hostname }}.p12"
```suggestion
        path: "{{ lookup('config', 'DEFAULT_LOCAL_TMP') | dirname }}/{{ ansible_hostname }}.p12"
```

I just foud a little bit of lint. ;-)

2024-11-15 14:11 UTC, widhalmt commented on roles/elasticsearch/tasks/elasticsearch-security.yml
> +        dest:  "{{ lookup('config', 'DEFAULT_LOCAL_TMP') | dirname }}/{{ ansible_hostname }}.p12_{{ ansible_date_time.iso8601_micro }}"
```suggestion
        dest: "{{ lookup('config', 'DEFAULT_LOCAL_TMP') | dirname }}/{{ ansible_hostname }}.p12_{{ ansible_date_time.iso8601_micro }}"
```
Same with extra spaces here.

2024-11-15 14:11 UTC, widhalmt commented on roles/elasticsearch/tasks/elasticsearch-security.yml
> +        path:  "{{ lookup('config', 'DEFAULT_LOCAL_TMP') | dirname }}/{{ ansible_hostname }}.p12"
```suggestion
        path: "{{ lookup('config', 'DEFAULT_LOCAL_TMP') | dirname }}/{{ ansible_hostname }}.p12"
```
I think, I see a pattern. :-)

2024-11-16 06:22 UTC, zerwes commented on roles/elasticsearch/tasks/elasticsearch-security.yml
> +        path:  "{{ lookup('config', 'DEFAULT_LOCAL_TMP') | dirname }}/{{ ansible_hostname }}.p12"
yes, somehow my search/replace vim regex seem to had a hiccup ... or it was rather pecak and not regex? Anyhow, thank you for you attention and suggestion.

2024-11-16 06:25 UTC, zerwes commented
> Oh, very good find! Thank you for the contribution.
> 
> I just found some tiny bits of lint. Could you please fix them and then I'll merge.

Thank you @widhalmt for the hint and suggestions and sorry for the error.
Now a `git grep ':  "{{'` in the repo is silent.

2024-11-26 09:19 UTC, merged