Enable ca/cert management
NETWAYS/ansible-collection-elasticstack pull request #58
Opened 2023-02-13 08:54 UTC by afeefghannam89

* Enable renew elasticsearch cert
* Enable renew Logstash cert
* Enable renew kibana cert
* Enable renew beats cert
* Let Logstash right data on disk
* Prevent Logstash to stick by elasticsearch dead connection
*  Fix #35

2023-02-13 13:39 UTC, widhalmt requested changes
I love how you work with tags everywhere and how you use tags for one-shot runs like when renewing certificates.

I'm not 100% sure if renewing client certificates wouldn't make sense as a variable. This way you could just enable it and have them replaced as soon as they close in on the end of their validity.

Most comments are things I'm wondering and I'm not really sure if there needs to be a change. Please don't read them as a request for an actual change. It's more of a "did you have time to test"?

The only real changes I see are that handlers are missing (we talked about that offline) and the per queue setting (with global default) of queue type and size.

2023-02-13 13:39 UTC, widhalmt commented on roles/elasticsearch/tasks/elasticsearch-security.yml
> +    - Restart Kibana
This handler is not available in this role, yet. We only have it in the `kibana` role. Please keep in mind, that most setups have an arbitrary number of Kibana hosts running on different hosts.

2023-02-13 13:39 UTC, widhalmt commented on docs/role-logstash.md
> +* *logstash_queue_type*: Where should Logstash right the data: (Default: `persisted`)
How about making the other setting (`memory`?) the default? Persisted queues can have a huge impact on Logstash, creating lots of I/O and slowing down the whole process. At least pipelines that receive messages from senders which can't deal with backpressure should be able to disable persistance.

2023-02-13 13:39 UTC, widhalmt commented on roles/beats/tasks/main.yml
> +      when: elastic_cert_pass is defined
```suggestion
      when: 
        - elastic_cert_pass is defined
        - beats_tls_key_passphrase is undefined
```
I guess syncing the two is only really neccessary when you use one single certificate for both services. As I understand, you cleaned that up. So I assume, it would work to have different passwords or even unique passwords per host.

2023-02-13 13:39 UTC, widhalmt commented on roles/elasticsearch/tasks/elasticsearch-security.yml
> +    - Restart Kibana
Same as above. That handler doesn't exist in this role.

2023-02-13 13:39 UTC, widhalmt commented on roles/elasticsearch/tasks/main.yml
> +  - elastic_cert_pass is defined
```suggestion
    - elastic_cert_pass is defined
```
I guess 2 spaces more of indentation are needed here.

2023-02-13 13:39 UTC, widhalmt commented on roles/logstash/defaults/main.yml
> +logstash_validate_after_inactivity: '0'
Does `0` work? I know, we discussed that but isn't that a bit aggressive for production use? I'm not sure myself I just want to be cautious.

2023-02-13 13:39 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
> +  when: not logstash_beats_tls_encryptkey | bool
Didn't you remove the other PKCS8 transformation? Do I read it right that, when `logstash_beats_tls_encryptkey` is set that there's no PKCS8 key generated at all?

2023-02-13 13:39 UTC, widhalmt commented on roles/logstash/tasks/logstash-security.yml
I guess, there's a way of moving the old PKCS8 key missing. Maybe I just missed it. But when the key is renewed completely, the PKCS8 variant won't be renewed, because the tasks only checks for the `creates`, right?

2023-02-13 13:39 UTC, widhalmt commented on roles/logstash/templates/pipelines.yml.j2
> +  queue.type: {{ logstash_queue_type }}
I'd love to have that configureable per pipeline and not globally. Falling back to a global default would be great, but we need a bit more flexibility than global settings. For both `queue.type` and `queue.max.bytes`.

2023-02-13 14:11 UTC, afeefghannam89 commented on roles/elasticsearch/tasks/elasticsearch-security.yml
> +    - Restart Kibana
Thanks for this good found :), I did not see it. I will make the suitable changes.

2023-02-13 14:13 UTC, afeefghannam89 commented on docs/role-logstash.md
> +* *logstash_queue_type*: Where should Logstash right the data: (Default: `persisted`)
What do you mean please with **other** other pipelines?

2023-02-13 14:22 UTC, afeefghannam89 commented on roles/logstash/tasks/logstash-security.yml
> +  when: not logstash_beats_tls_encryptkey | bool
You are right, I found this after pushing and it is already in. the next push with I did not make yet. It did not catch it during master rebaise

2023-02-13 14:54 UTC, afeefghannam89 commented
> I love how you work with tags everywhere and how you use tags for one-shot runs like when renewing certificates.
> 
> I'm not 100% sure if renewing client certificates wouldn't make sense as a variable. This way you could just enable it and have them replaced as soon as they close in on the end of their validity.
> 
> Most comments are things I'm wondering and I'm not really sure if there needs to be a change. Please don't read them as a request for an actual change. It's more of a "did you have time to test"?
> 
> The only real changes I see are that handlers are missing (we talked about that offline) and the per queue setting (with global default) of queue type and size.

I like tags more, because they are more flexible by management of changes, the user should not change any variable value when he would like to run a snippet of Ansible code. The variable will come later when we check the validity of certificate. This variable will be set to the conditions of certificate renew tasks. So the user does not have to manipulate any variable value, this will enforce automatism Principe

2023-02-13 15:51 UTC, widhalmt commented on docs/role-logstash.md
> +* *logstash_queue_type*: Where should Logstash right the data: (Default: `persisted`)
Ususally we have more than one pipeline in a Logstash configuration and in `pipelines.yml`. I'd prefer to set `logstash_queue_type` and `logstash_queue_memory_max_bytes` different per pipeline. Not one global value for all of them.

See #60 . It's an old issue from the deprecated role but we already thought about the same thing.

2023-02-14 20:38 UTC, afeefghannam89 commented on roles/logstash/templates/pipelines.yml.j2
> +  queue.type: {{ logstash_queue_type }}
Thanks for the advice :) done

2023-02-14 20:39 UTC, afeefghannam89 commented on roles/logstash/defaults/main.yml
> +logstash_validate_after_inactivity: '0'
I raised it to 300 = 5 minutes

2023-02-14 20:41 UTC, afeefghannam89 commented on roles/beats/tasks/main.yml
> +      when: elastic_cert_pass is defined
Ahhh good notice, I updated it

2023-02-14 20:43 UTC, afeefghannam89 commented on docs/role-logstash.md
> +* *logstash_queue_type*: Where should Logstash right the data: (Default: `persisted`)
I hope it is now more flexible see please last pushes :)

2023-02-14 20:59 UTC, afeefghannam89 commented on roles/logstash/tasks/logstash-security.yml
The complete Logstash certificate directory will be backed up and removed, so no need to move files individually ;)

2023-02-16 13:14 UTC, widhalmt requested changes
Wow, that was a big one to review. :-)

The only real change I can request is the missing "newline" character. The rest is more "I'm not sure, can you give me information about it". So I guess, it's very close to being finished.

The "boolean" for the queue type was just an idea. I guess, it's not worth editing everything again just for that.

2023-02-17 08:27 UTC, widhalmt commented
Please merge `main` into this branch. It should help with fixing some problems.

2023-02-17 11:22 UTC, widhalmt commented on roles/logstash/templates/pipelines.yml.j2
> +  queue.type: {{ logstash_queue_type }}
Thanks. :-)

2023-02-17 12:59 UTC, widhalmt commented
I fixed some lint so checks can go through. I'm right now testing this on a local system.

2023-02-17 17:05 UTC, widhalmt commented
Changing the Logstash certificate works for me. But only for the `elasticsearch` output, not for `monitoring` Since `xpack.monitoring` was deprecated with Elastic Stack 7 anyway, I'll add a condition so that it will be removed from 8 setups.

2023-02-20 00:12 UTC, afeefghannam89 commented on roles/kibana/tasks/kibana-security.yml
> +   - Restart Elasticsearch for Kibana certificates
Thanks you are right I have remove it.

2023-02-20 00:16 UTC, afeefghannam89 commented on roles/beats/handlers/main.yml
> +  when: beats_filebeat | bool
When the certificate will be changed, the beat services have to be restarted, right?
So when we stay with for example  *auditbeat_enable | bool* as condition and auditbeat is not installed, but it is enabled as default, then Ansible will throw an error saying that auditbeat service is not available.

2023-02-20 00:20 UTC, afeefghannam89 commented on docs/role-logstash.md
> +* *logstash_queue_type*: Where should Logstash right the data: (Default: `persisted`)
This version is not bad also :)

2023-02-20 09:47 UTC, afeefghannam89 commented
@widhalmt I am fixing Lint now

2023-02-20 10:23 UTC, widhalmt commented
> @widhalmt I am fixing Lint now

We have some other Pull requests which might fix this already. Have a look, maybe it only needs a Review to be merged and then you can safe that pesky work.

2023-02-20 10:27 UTC, widhalmt commented on roles/beats/handlers/main.yml
> +  when: beats_filebeat | bool
Right! Good catch. So we need both conditions, I guess.

2023-02-20 11:48 UTC, widhalmt requested changes
I just found one typo and 2 missing prefixes for variable names. Everything else looks not just good but excellent to me!

2023-02-20 11:48 UTC, widhalmt commented on docs/role-beats.md
> +* *beats_cert_will_expire_soon*: Set it to true to renew beats certificate (default: `fasle`), Or run the playbook with `--tags renew_beats_cert` to do that.
```suggestion
* *beats_cert_will_expire_soon*: Set it to true to renew beats certificate (default: `false`), Or run the playbook with `--tags renew_beats_cert` to do that.
```

2023-02-20 11:48 UTC, widhalmt commented on roles/elasticsearch/defaults/main.yml
> +ca_expiration_buffer: 30
```suggestion
elastic_ca_expiration_buffer: 30
```

Please keep the prefix. Otherwise you might have collisions with our `ca` role

2023-02-20 11:48 UTC, widhalmt commented on roles/elasticsearch/defaults/main.yml
> +ca_will_expire_soon: false
```suggestion
elastic_ca_will_expire_soon: false
```

Please keep the prefix. Otherwise you might have collisions with our `ca` role

2023-02-20 12:51 UTC, afeefghannam89 commented on roles/elasticsearch/defaults/main.yml
> +ca_will_expire_soon: false
Done.

2023-02-20 12:51 UTC, afeefghannam89 commented on roles/elasticsearch/defaults/main.yml
> +ca_expiration_buffer: 30
Done.

2023-02-20 12:51 UTC, afeefghannam89 commented on docs/role-beats.md
> +* *beats_cert_will_expire_soon*: Set it to true to renew beats certificate (default: `fasle`), Or run the playbook with `--tags renew_beats_cert` to do that.
Done

2023-02-20 12:52 UTC, afeefghannam89 commented on roles/beats/handlers/main.yml
> +  when: beats_filebeat | bool
Done.

2023-02-20 17:41 UTC, merged